export const translateVar = {
	RU: {
		1:'Формула',
		2:'Магазин',
		3:'О нас',
		4:'Блог',
		5:'Контакты',
		6:'Карта',
		7:'Магазин →',
		8:'ОБЕЩАНИЕ Pauli',
		9:'Pauli & Sisters уверены, что вы можете оздоровить свою кожу, используя идеальный баланс натуральных масел. Наш продукт разработан для устранения сухости, неровного тона кожи, рубцов и растяжек. Мы используем только качественные средства.',
		10:'О нас →',
		11:'Летняя рубашка',
		12:'Ограниченное предложение -',
		13:'Восстанавливающая сыворотка',
		14:'Многофункциональное масло, обогащенное 11 питательными веществами, растительными компонентами.',
		15:'Объём',
		16:'1.8 Жидкая унция / 52 мл',
		17:'Количество',
		18:'Цена',
		19:'Добавить в корзину →',
		20:'11 ТЩАТЕЛЬНО ПОДОБРАННЫХ ИНГРЕДИЕНТОВ',
		21:'Все начинается с того, что каждый ингредиент - это главный ингредиент. Мы не добавляем в нашу формулу ингредиенты в маркетинговых целях. В Pauli & Sisters 11 ингредиентов, каждый из которых тщательно разрабатывается в течение 2 лет, чтобы подарить вашей коже любовь, которой она заслуживает.',
		22:'Узнать больше →',
		23:'Миндальный',
		24:'Семена омеги',
		25:'Шиповник',
		26:'Черная смородина',
		27:'Редис с дайконом',
		28:'Естественное решение проблем с уходом за кожей',
		29:'на 100% растительной основе, с тщательно подобранными ингредиентами, которые защищают вашу кожу от внешних воздействий. Наши масла стимулируют выработку клеток и коллагена, снимают воспаление, заживляют рубцы, устраняют гиперпигментацию и улучшают кровообращение в коже.',
		30:'Магазин →',
		31:'Доступная роскошь',
		32:'Косметика Pauli & Sisters создана с учетом интересов каждого человека. Наши натуральные ингредиенты позволяют вам наслаждаться роскошью ухода за кожей с помощью натуральных ингредиентов, не тратя на это ни копейки.',
		33:'Магазин →',
		34:'Никаких токсинов',
		35:'Без консервантов',
		36:'100% веганский продукт',
		37:'Органический продукт',
		38:'Получайте последние обновления от Pauli & Sisters',
		39:'Подписаться →',
		40:'Купить сейчас →',
		41:'Подписывайтесь  @pauliandsisters →',
		42:'Подписаться',
		43:'Информация',
		44:'Контакты',
		45:'Политика конфиденциальности',
		46:'Правила & условия',
		47:'Возврат',
		48:'Не продавайте мою личную информацию',
		49:'Сделано в США',
		50:'Изготовлено компанией Conscious Planet, Ирвин, Калифорния, 92614',
		51:'Стань героем для кого-нибудь',
		52:'Каждой покупкой в Pauli & Sisters вы помогаете всем женщинам и детям, ставшим жертвами секс-торговли. 1 $ от вашей покупки будет передан благотворительному фонду Thorn для поддержки борьбы с торговлей детьми в целях сексуальной эксплуатации.',
		53:'Свяжитесь с нами',
		54:'Если вы желаете связаться с нами, заполните форму и оставьте сообщение.',
		55: 'Мы на карте',
		56: 'Отправить →',
		57: 'Купить',
		58:'Моя корзина',
		59:'Товар',
		60:'ИТОГО',
		61:'Доставка: 20$',
		62:'Оплатить картой',
		63:'Изменить карту',
		64:' Я соглашаюсь с ',
		65:'Политикой конфиденциальности',
		66:'Итого',
		67:'Почта',
		68:'Телефон',
		69:'Возраст',
		70:'Адрес',
		71:'Моя карта',
		72:'Мои заказы',
		74:'Цена',
		75:'Дата'
	},
	EN: {
		1:'Formulation',
		2:'Shop',
		3:'About',
		4:'Blog',
		5:'Contact',
		6:'Cart',
		7:'Shop →',
		8:'The Pauli Promise',
		9:'At Pauli & Sisters we believe that you can heal your skin with the perfect balance of natural oils. Our product is formulated to correct dryness, uneven skin tone, scarring, and stretch marks. We’re all about using only the good stuff.',
		10:'About us →',
		11:'Summer Shirt',
		12:'Limited Offer – ',
		13:'Repair Serum',
		14:'A multi-correctional oil infused with 11 hero nutrient-rich botanicals.',
		15:'Size',
		16:'1.8 fl.oz / 52 ml',
		17:'Quantity',
		18:'Price',
		19:'Add to cart →',
		20:'11 CAREFULLY FORMULATED INGREDIENTS',
		21:'It starts with every ingredient being a hero ingredient. We don’t pack our formula with ingredients for marketing purposes. Pauli & Sisters has 11 ingredients each carefully formulated over a 2 year period to give your skin the love it deserves.',
		22:'Discover more →',
		23:'Almond',
		24:'Omega Seed',
		25:'Rosehip',
		26:'Black Currant',
		27:'Daikon Radish',
		28:'Natural solution to skincare problems',
		29:'100% plant based with carefully picked ingredients to serve your skin’s greatest barriers. Our oils do everything from boosting cell and collagen production, to easing inflammation, healing scarring, and evening the hyper-pigmentation and circulation to the skin.',
		30:'Shop →',
		31:'Affordable Luxury',
		32:'Pauli & Sisters is made with everyone in mind. Our natural ingredients give you the luxury of healing your skin with natural ingredients without having to pay an arm and a leg for it.',
		33:'Shop →',
		34:'No toxins',
		35:'No preservatives',
		36:'100% vegan',
		37:'Organic',
		38:'Get the latest Pauli & Sisters updates',
		39:'Subscribe →',
		40:'Shop now →',
		41:'Follow  @pauliandsisters →',
		42:'Follow',
		43:'Info',
		44:'Contact Us',
		45:'Privacy Policy',
		46:'Terms & Conditions',
		47:'Returns',
		48:'Do not sell my personal information',
		49:'Made in USA',
		50:'Manufactured by Conscious Planet,  Irvine, California 92614',
		51:'Be a hero to someone',
		52:'With every purchase of Pauli & Sisters, you are supporting all the women and children that are victims of sex trafficking. $1 of your purchase will go to the Thorn Charity to support the fight against child sex trafficking and sexual exploitation of children.',
		53:'Contact Us',
		54:'If you would like to contact us, fill out the form and leave a message.',
		55:'We are on the map',
		56: 'Send message →',
		57:'Buy it',
		58:'Your cart',
		59:'ITEM',
		60:'SUBTOTAL',
		61:'Delivery: 20$',
		62:'Pay by card',
		63:'Change card',
		64:' I agree ',
		65:'Privacy Policy',
		66:'Cart Total:',
		67:'Mail',
		68:'Phone',
		69:'Age',
		70:'Address',
		71:'My Card',
		72:'My orders:',
		74:'Price',
		75:'Date'
	}
}